version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
            - ./xmlsRio/:/var/www/storage/xmls/rio 
            - ./logs/:/var/www/storage/app/
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
